import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/ui/nav/nav";
import Footer from "@/ui/footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "云朵视界",
  description: "Generated by create Hanke ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <div className="grid grid-rows-[68px_1fr_68px] min-h-screen">
        <div className="bg-gray-100 flex items-center justify-center">
            <Nav/>
        </div>
        <div className="bg-gray-100 flex items-center justify-center">
            {children}
        </div>
        <div className={"bg-gray-100 flex items-center justify-center"}>
            <Footer/>
        </div>
    </div>

    </body>
    </html>
  );
}
